package main

import (
	"fmt"
	//	"time"

	"pd.com/md/m7Logger"
)

var count = 0

func main() {

	a1, err := m7Logger.InitLogger("dfkjdskj", "log1.log", 1024, 3)
	a2, errr := m7Logger.InitLogger("dfkjdfd", "log2.log", 1024, 3)
	a3, _ := m7Logger.InitLogger("dfkjddfd", "log3.log", 1024, 3)
	/*		a4, _ := m7Logger.InitLogger("dfkjddfd", "log4.log", 1024, 3)
			a5, _ := m7Logger.InitLogger("dfkjdfdf", "log5.log", 1024, 3)
			a6, _ := m7Logger.InitLogger("dfkjddff", "log6.log", 1024, 3)
			a7, _ := m7Logger.InitLogger("dfkjdfdf", "log7.log", 1024, 3)
			a8, _ := m7Logger.InitLogger("dfkjdfdf", "log8.log", 1024, 3)
			a9, _ := m7Logger.InitLogger("dfkjdfdf", "log9.log", 1024, 3)
			a10, _ := m7Logger.InitLogger("dfkjdfdf", "log10.log", 1024, 3)
			a11, _ := m7Logger.InitLogger("dfkjdfdf", "log11.log", 1024, 3)
			a12, _ := m7Logger.InitLogger("dfkjdfdf", "log12.log", 1024, 3)
			a13, _ := m7Logger.InitLogger("dfkjdfdf", "log13.log", 1024, 3)
			a14, _ := m7Logger.InitLogger("dfkjdfdf", "log14.log", 1024, 3)
			a15, _ := m7Logger.InitLogger("dfkjdfdf", "log15.log", 1024, 3)
			a16, _ := m7Logger.InitLogger("dfkjdfdf", "log16.log", 1024, 3)
			a17, _ := m7Logger.InitLogger("dfkjdfdf", "log17.log", 1024, 3)
			a18, _ := m7Logger.InitLogger("dfkjdfdf", "log18.log", 1024, 3)
			a19, _ := m7Logger.InitLogger("dfkjdfdf", "log19.log", 1024, 3)
			a20, _ := m7Logger.InitLogger("dfkjdfdf", "log20.log", 1024, 3)*/

	//	h, errr := pankajDubey.InitLogger("dfkjd", "log2.log", 1024, 3)

	if err == 1 || errr == 1 {
		fmt.Println("something wrong")
	} else {
		//	fmt.Println(d.LogErr)
		//	fmt.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")

		for i := 0; i < 30; i++ {
			a1.FileSize()
			//	time.Sleep(2 * time.Second)
			a1.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>1>>>>>>>>>>>>>>>", count)
			a1.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>1>>>>>>>>>>>", count)
			a1.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>1>>>>>>>>>>>", count)
			a1.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>1>>>>>>>>>>>>>>>", count)
			a2.FileSize()
			a2.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>2>>>>>>>>>>>>>>>>", count)
			a2.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>2>>>>>>>>>>>", count)
			a2.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>2>>>>>>>>>>>", count)
			a2.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>2>>>>>>>>>>>", count)
			a3.FileSize()
			a3.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>3>>>>>>>>>>>>>>>", count)
			a3.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>3>>>>>>>>>>", count)
			a3.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>3>>>>>>>>>", count)
			a3.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>3>>>>>>>>>", count)
			/*	a4.FileSize()
				a4.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>4>>>>>>>>>>>>>>>", count)
				a4.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>4>>>>>>>>>>", count)
				a4.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>4>>>>>>>>>>", count)
				a4.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>4>>>>>>>>>>", count)
				a5.FileSize()
				a5.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>5>>>>>>>>>>>>>>>", count)
				a5.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>5>>>>>>>>>>", count)
				a5.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>5>>>>>>>>>", count)
				a5.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>5>>>>>>>>>", count)
				a6.FileSize()
				a6.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>6>>>>>>>>>>>>>>", count)
				a6.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>6>>>>>>>>>", count)
				a6.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>6>>>>>>>>", count)
				a6.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>6>>>>>>>>", count)
				a7.FileSize()
				a7.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>7>>>>>>>>>>>>>", count)
				a7.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>7>>>>>>>>", count)
				a7.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>7>>>>>>>", count)
				a7.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>7>>>>>>>", count)
				a8.FileSize()
				a8.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>8>>>>>>>>>>>>>", count)
				a8.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>8>>>>>>>>", count)
				a8.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>8>>>>>>>", count)
				a8.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>8>>>>>>>", count)
				a9.FileSize()
				a9.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>9>>>>>>>>>>>>>", count)
				a9.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>9>>>>>>>>", count)
				a9.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>9>>>>>>>", count)
				a9.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>9>>>>>>>", count)
				a10.FileSize()
				a10.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>10>>>>>>>>>>>>>", count)
				a10.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>10>>>>>>>>", count)
				a10.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>10>>>>>>>", count)
				a10.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>10>>>>>>>", count)
				a11.FileSize()
				a11.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>11>>>>>>>>>>>>>", count)
				a11.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>11>>>>>>>>", count)
				a11.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>11>>>>>>>", count)
				a11.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>11>>>>>>>", count)
				a12.FileSize()
				a12.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>12>>>>>>>>>>>>>", count)
				a12.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>12>>>>>>>>", count)
				a12.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>12>>>>>>>", count)
				a12.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>12>>>>>>>", count)
				a13.FileSize()
				a13.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>13>>>>>>>>>>>>>", count)
				a13.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>13>>>>>>>>", count)
				a13.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>13>>>>>>>", count)
				a13.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>13>>>>>>>", count)
				a14.FileSize()
				a14.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>14>>>>>>>>>>>>>", count)
				a14.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>14>>>>>>>>", count)
				a14.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>14>>>>>>>", count)
				a14.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>14>>>>>>>", count)
				a15.FileSize()
				a15.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>15>>>>>>>>>>>>>", count)
				a15.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>15>>>>>>>>", count)
				a15.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>15>>>>>>>", count)
				a15.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>15>>>>>>>", count)
				a16.FileSize()
				a16.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>16>>>>>>>>>>>>>", count)
				a16.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>16>>>>>>>>", count)
				a16.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>16>>>>>>>", count)
				a16.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>16>>>>>>>", count)
				a17.FileSize()
				a17.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>17>>>>>>>>>>>>>", count)
				a17.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>17>>>>>>>>", count)
				a17.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>17>>>>>>>", count)
				a17.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>17>>>>>>>", count)
				a18.FileSize()
				a18.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>18>>>>>>>>>>>>>", count)
				a18.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>18>>>>>>>>", count)
				a18.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>18>>>>>>>", count)
				a18.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>18>>>>>>>", count)
				a19.FileSize()
				a19.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>19>>>>>>>>>>>>>", count)
				a19.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>19>>>>>>>>", count)
				a19.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>19>>>>>>>", count)
				a19.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>19>>>>>>>", count)
				a20.FileSize()
				a20.LogInfo.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>20>>>>>>>>>>>>>", count)
				a20.LogWarn.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>20>>>>>>>>", count)
				a20.LogErr.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>20>>>>>>>", count)
				a20.LogHverb.Println(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>20>>>>>>>", count)
			*/

			count += 1

		}

	}

}
